name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Run Kotlin Linter
      run: ./gradlew ktlintStagingDebugCheck
    - name: Run Unit Tests
      run: ./gradlew testStagingDebugUnitTest
      
    # Espresso testing for Android Views
    - uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
        target: default
        arch: x86
        profile: Nexus 6
        script: ./gradlew connectedCheck --stacktrace
